// <auto-generated />
namespace blog.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class alteredsomefieldsonblogPostdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteredsomefieldsonblogPostdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202412101249265_altered-some-fields-on-blogPost-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
